language: go
sudo: false
go:
  - 1.7
  - 1.8
  - 1.9
  - master

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:
  - go get -t -v ./...

script:
  - $GOPATH/bin/goveralls -service=travis-ci
